[book]
authors = ["Sébastien Wilmet", "Gerson Benavides"]
language = "es"
multilingual = false
src = "src"
title = "La plataforma de desarrollo GLib/GTK"


[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
# google-analytics = "G-2BG5WVZ08D"
additional-css = ["./src/assets/css/custom.css"]
additional-js = [
    "./src/assets/js/refs-ch.js",
    "./src/assets/js/refs-biblio.js",
    "./src/assets/js/refs-intro.js",    
    "./src/assets/js/refs-glib.js",
    "./src/assets/js/refs-oop-semi.js",
    "./src/assets/js/refs-oop-gobj.js",
    "./src/assets/js/refs-gtk-app-arch.js"
]
git-repository-url = "https://github.com/gersonbdev/glib-gtk-libro"
git-repository-icon = "fa-github"
site-url = "/glib-gtk-libro/"
