[book]
authors = ["Sébastien Wilmet", "Gerson Benavides"]
language = "es"
multilingual = false
src = "src"
title = "La plataforma de desarrollo GLib/GTK"


[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["./src/assets/css/custom.css"]
additional-js = [
    "./src/assets/js/refs.js"
]
git-repository-url = "https://github.com/gersonbdev/glib-gtk-libro"
git-repository-icon = "fa-github"
site-url = "/glib-gtk-libro/"
