[book]
authors = ["Sébastien Wilmet", "Gerson Benavides"]
language = "es"
multilingual = false
src = "src"
title = "La plataforma de desarrollo GLib/GTK"


[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
google-analytics = "G-2BG5WVZ08D"
additional-css = ["./src/assets/css/custom.css"]
git-repository-url = "https://github.com/gersonbdev/glib-gtk-libro"
git-repository-icon = "fa-github"
